import { ColumnDef } from '@tanstack/react-table';

import { IUser } from '../../models/User';

export const columns: ColumnDef<IUser>[] = [
  {
    header: 'NAME',
    id: 'name',
    accessorFn: (row) => `${row.firstName} ${row.lastName}`,
    minSize: 50,
    size: 200,
    maxSize: 200,
    enableSorting: true,
    enableColumnFilter: true,
    enableResizing: true,
    enablePinning: true,
  },
  {
    header: 'EMAIL',
    id: 'email',
    accessorKey: 'personalInfo.contactInfo.workEmail',
    minSize: 50,
    size: 200,
    maxSize: 200,
    enableSorting: true,
    enableColumnFilter: true,
    enableResizing: true,
    enablePinning: true,
  },
  {
    header: 'STATUS',
    id: 'status',
    accessorKey: 'personalInfo.status',
    minSize: 50,
    size: 200,
    maxSize: 200,
    enableSorting: true,
    enableColumnFilter: true,
    enableResizing: true,
    enablePinning: true,
  },
  {
    header: 'SPECIALTY',
    id: 'specialty',
    accessorKey: 'personalInfo.otherInfo.specialty',
    minSize: 50,
    size: 200,
    maxSize: 200,
    enableSorting: true,
    enableColumnFilter: true,
    enableResizing: true,
    enablePinning: true,
  },
  {
    header: 'FACILITY',
    id: 'facility',
    accessorKey: 'personalInfo.facility',
    minSize: 50,
    size: 200,
    maxSize: 200,
    enableSorting: true,
    enableColumnFilter: true,
    enableResizing: true,
    enablePinning: true,
  },
  {
    header: 'CREDENTIALING',
    id: 'credentialing',
    accessorKey: 'personalInfo.otherInfo.credentialing',
    minSize: 50,
    size: 200,
    maxSize: 200,
    enableSorting: true,
    enableColumnFilter: true,
    enableResizing: true,
    enablePinning: true,
  },
];
